### ISSUE TITLE
Undefined references when building on aarch64

### ISSUE THREAD

**Issue by pgrt** [ugeneunipro/ugene#1681]
Hi,

I am the maintainer of ugene in Debian. Version 51 fails to build on aarch64:
https://buildd.debian.org/status/fetch.php?pkg=ugene&arch=arm64&ver=51.0%2Bdfsg-1&stamp=1727989828&raw=0

I could fix it by removing the exposed signatures of _neon methods (enclosed patch), but certainly one can do better.

All the best,

Pierre
[undefined_references.txt](https://github.com/user-attachments/files/17259068/undefined_references.txt)

**Comment by DmitriiSukhomlinov** [comment]
Hello,

This is not the best solution for this problem. Build fails because some arm-specific functions are defined in some .h file (and, probably, are in use somewhere else), but not implemented in .c file. It happens because we do not support native arm build for now, so we just do not follow this case. We have a special issue for supporting this and, deffinetely, when this issue will be in progress we will find and resolve the relative problem in the htslib tool. For now, the suggested solution is not correct.
