### ISSUE TITLE
efficient way of exporting consensus sequence

### ISSUE THREAD

**Issue by computingmachine** [ugeneunipro/ugene#44]
Hi,

Is there an efficient way to export the consensus sequence when the data is fairly large? I try to export the chromosome 1 and the Ugene stopped working. I am wondering if there is linux command or other ways can handle this.

Thanks,

**Comment by atiunov** [comment]
Does the UGENE hangs at all? Or it is just calculating something on the background without any results, but you can do something else, for example, open another file?
The consensus exporting can take some time, because there is need to scan the whole file, which is rather big. It took 20 minutes on my computer. You can see a message about export task execution at the bottom of the UGENE window.
You can use samtools to do get the consensus sequence, if you have the reference sequence: [see samtools documentation](https://samtools.github.io/bcftools/howtos/consensus-sequence.html).

**Comment by yalgaer** [comment]
Closing: no feedback from the reporter.
