### ISSUE TITLE
Primers are limited in size

### ISSUE THREAD

**Issue by Tmarinus** [ugeneunipro/ugene#648]
https://github.com/ugeneunipro/ugene/blob/8065b4e584493e86a8b5fcbce41f894e7b42f52d/src/corelibs/U2Core/src/datatype/primers/PrimerStatistics.h#L47-L51

Primer search have an artificial limit in maximum and minimum size. While less common it can still be the case that you have primers that are smaller or larger than 15/50 bases. (Personally I got this issue when I had primers of 54 bases.) 

I did a brief build of Ugene with the maximum increased to 200 (a common maximum primer size when ordering oligos) and this seems to work fine.

**Comment by yalgaer** [comment]
Hi,
We introduced the limit only because of some memory issues caused by very short "primers": the computation process was very slow because of too many matches and could even trigger out of memory errors. 

The MIN and MAX limits in the code were set satisfy if not all but >99% our users who look for primers in 18-30 range with reasonable melting temperatures.

I'm will increase the MAX limit from 50 to 200 as you suggested.

**Comment by Tmarinus** [comment]
@yalgaer Thank you for the quick response and fix.
