### ISSUE TITLE
[regression] In 42.0 many paths changed and now it installs files into wrong locations

### ISSUE THREAD

**Issue by yurivict** [ugeneunipro/ugene#849]
For example, before ```UGENE_INSTALL_DIR``` allowed caller to change data directory.
Now it just installs into $${PREFIX}/data which doesn't match where package data is expected to be installed.

The executable is now installed into ```${PREFIX}/ugene``` instead of ```${PREFIX}/bin/ugane```.

Using qmake build on FreeBSD 13.1

**Comment by yalgaer** [comment]
When UGENE is built from sources a user can specify only 1 single directory using 'PREFIX'. 
The whole UGENE package (binaries, data, plugins, external tools) will be installed into this directory as the result of the build.

We do not split package into separate folders like it is done on many Linux/Unix systems, because there is no single standard about the correct locations. So we follow a simpler logic: the application package (like on MacOS).

If you want to support a special 'multi-folder' build/install mode for FreeBSD we will be happy to accept a patch for it.

**Comment by yalgaer** [comment]
Closing as inactive. Please reopen if needed

**Comment by yurivict** [comment]
But why was this changed in 42.0? Paths were fine before that.

Installing into commonly accepted file structure doesn't contradict the ability to install into any prefix.
